# Generated by Django 4.2.2 on 2023-06-11 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingredient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('steps', models.TextField()),
                ('ingredients', models.ManyToManyField(to='ingredient.ingredient')),
            ],
        ),
    ]
